---
- name: register required resources
  include: register_vpc.yml

- name: register kubernetes firewall
  gcp_compute_firewall:
    name: "{{ firewall_master_name }}"
    network: "{{ network }}"
    allowed:
      - ip_protocol: tcp
        ports: ['2379','2380', '6443', '8090', '8091', '10250', '10251', '10252', '10255']
      - ip_protocol: udp
        ports: ['8472']
    source_ranges: ['0.0.0.0/0']
    project: "{{ gcp_project_name }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
  register: firewall