---
- name: create a vpc network
  gcp_compute_network:
    name: "{{ network_name }}"
    auto_create_subnetworks: yes
    project: "{{ gcp_project_name }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    state: present
  register: network

- name: create a route (subnetwork)
  gcp_compute_subnetwork:
    name: "{{ subnet_name }}"
    region: "{{ gcp_region }}"
    network: "{{ network }}"
    ip_cidr_range: "{{ ip_cidr_range }}"
    project: "{{ gcp_project_name }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    state: present
  register: subnet
