---
- name: register the dependent resources
  include: register_master_firewall.yml

- name: delete an instance for worker1
  gcp_compute_instance:
    name: "{{ instance2_name }}"
    zone: "{{ gcp_zone }}"
    project: "{{ gcp_project_name }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    state: absent

- name: delete an address for worker1
  gcp_compute_address:
    name: "{{ instance2_name }}"
    region: "{{ gcp_region }}"
    project: "{{ gcp_project_name }}"
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_service_account_file }}"
    state: absent
