---
- name: get join command (token)
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"


- name: copy the token into a temporary file
  copy:
    content: "{{ join_command }}"
    dest: /tmp/joiningk8sthecluster.sh


- name: download the token file to local machine
  fetch:
    src: /tmp/joiningk8sthecluster.sh
    dest: "{{ role_path }}/files/joiningk8sthecluster.sh"
    flat: yes
